; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; upload_port = COM4     ; descomentar y ajustar si hace falta forzar el puerto
; monitor_port = COM4

; Necesario para que compile el TimerConfig.cpp que está en include/
; (por default, PlatformIO solo compila los .cpp de src/ y lib/<carpeta>/)
build_src_filter = +<*> +<../include/*.cpp>

lib_deps =
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/DHT sensor library@^1.4.4
    adafruit/RTClib@^2.1.4
    nrf24/RF24@^1.6.0